data:
  - name: "SQ4 UAT CardX Wealth MFT"
    project_name: "CardX - User Acceptance Testing"
    version_name: "Wealth Post-Greenfield Jan 2026"
    cycle_name: "SQ4"
    webhook_path: "/macros/s/AKfycbyCtlQevEidDsOwL7RPPvNGnn9KOFh1zvLsmwlQ6eM6u9Y8kXaRXwIXuut4YMHKlqnPdw/exec"
    env: "UAT"
  - name: "SQ4 REG CardX Wealth MFT"
    project_name: "CardX - User Acceptance Testing"
    version_name: "Wealth Post-Greenfield Jan 2026"
    cycle_name: "SQ4-Regression"
    webhook_path: "/macros/s/AKfycbwbqVlXYKziHpZVNKwhow1XXTWNhH1s-zB96OnijN_2InYSGJKq1kIsompuK5uT0Ew-/exec"
    env: "UAT"