data:
  - name: "VB Borrowing MVP1.5 CR"
    project_name: "VB Goofy"
    version_name: "MVP1.5"
    cycle_names:
      - "5.Borrowing_REG_CR MA ศปอท"
      - "5.Borrowing_CR_New field for amortization table"
    webhook_path: "/macros/s/AKfycbymeo49cdPVazoQhBQpu0lIVqQFt9UPdqRRIgKfNN6fBmcjbevMoHlbGx281cYq7RZg/exec"
    env: "CR"
  # - name: "VB Borrowing MVP1.5 UAT"
  #   project_name: "VB Goofy"
  #   version_name: "MVP1.5"
  #   cycle_names:
  #     - "5.Borrowing_DRLoanManagement_Android"
  #     - "5.Borrowing_DRLoanManagement_iOS"
  #   webhook_path: "/macros/s/AKfycbxK8rDJAlPIcEwr_nzwBSU9hK-HuCC27J6xF5N42KxQ4gefd_1yRUZF8_R1_IpO5NjZ/exec"
  #   env: "SIT"
  # - name: "VB Borrowing MVP1.0 REG"
  #   project_name: "VB Goofy"
  #   version_name: "MVP1_Reg"
  #   cycle_names:
  #     - "5.Borrowing_AND_Reg"
  #     - "5.Borrowing_EN_Reg"
  #     - "5.Borrowing_iOS_Reg"
  #   webhook_path: "/macros/s/AKfycbzxV2U_a_xCkvcwQ7RSMBIkaGD1SjS1ZZfcLY_y95-Ine-fWdJlAqDw0QwwSc-6EjxI/exec"
  #   env: "REG"
  # - name: "VB Borrowing MVP1.0 UAT R2"
  #   project_name: "VB Goofy"
  #   version_name: "MVP1"
  #   cycle_names:
  #     - "5.Borrowing_EN"
  #     - "5.Borrowing_TH_AND"
  #     - "5.Borrowing_TH_iOS"
  #   webhook_path: "/macros/s/AKfycbxwsEkPzkbrQKBLnOqnCnT8awZ-OSR_KEZbcv0csATuXvkGqYhyckvLFuBDs_04mNLzpA/exec"
  #   folders:
  #     - "1.ApplyLoan-ETB"
  #     - "2.ApplyLoan-NTB"
  #     - "3.Disbursement"
  #     - "4.ManageLoan"
  #     - "5.Repayment"
  #     - "6.SelfServices"
  #     - "7.Close_Account(LOC)"
  #     - "8.TC_Deferred_From MVP0.5"
  #   env: "UAT"
  # - name: "VB Borrowing MVP1.0 UAT REG"
  #   project_name: "VB Goofy"
  #   version_name: "MVP1"
  #   cycle_names:
  #     - "5.Borrowing_TH_AND"
  #     - "5.Borrowing_TH_iOS"
  #   webhook_path: "/macros/s/AKfycbxwsEkPzkbrQKBLnOqnCnT8awZ-OSR_KEZbcv0csATuXvkGqYhyckvLFuBDs_04mNLzpA/exec"
  #   folders:
  #     - "3.Disbursement"
  #     - "4.ManageLoan"
  #     - "5.Repayment"
  #     - "6.SelfServices"
  #     - "7.Close_Account(LOC)"
  #     - "8.TC_Deferred_From MVP0.5"
  #   env: "SIT"
  # - name: "VB Borrowing MVP1.0 UAT R3"
  #   project_name: "VB Goofy"
  #   version_name: "MVP1"
  #   cycle_names:
  #     - "5.Borrowing_Release#3_AND"
  #     - "5.Borrowing_Release#3_iOS"
  #     - "5.Borrowing_Release#3_EN"
  #     - "5.Borrowing_Release#3_LOC_Eligibility_Validation"
  #   webhook_path: "/macros/s/AKfycbzX0TDlKA_8uZs3dBUDimMZetHoaz5yL-GForQcW4JMV2qs17y1Pk0IUJhZwsMmHYCQeQ/exec"
  #   env: "R3"